### ISSUE TITLE
TEST: moltenvk forumlae by mimic the official way but with homebrew code syntax

### ISSUE THREAD

**Issue by sl1pkn07** [rafaga/homebrew-r2k#7]
Hi, i've created a formula of moltenvk using the contents of the official script `fetchDependencies` and mimic the behavior using the homebrew code syntax

~~~ruby
class Moltenvk < Formula
  desc "Implementation of the Vulkan 1.0 API, that runs on Apple's Metal API"
  homepage "https://github.com/KhronosGroup/MoltenVK"
  url "https://github.com/KhronosGroup/MoltenVK.git", :tag => "v1.0.33"
  head "https://github.com/KhronosGroup/MoltenVK.git"

  depends_on "cereal" => :build
  depends_on "cmake" => :build
  depends_on "ninja" => :build
  depends_on "python" => :build
  depends_on :xcode => :build

  resource "Vulkan-Headers" do
    revi = Utils.popen_read("cat #{HOMEBREW_CACHE}/moltenvk--git/ExternalRevisions/Vulkan-Headers_repo_revision").chomp
    url "https://github.com/KhronosGroup/Vulkan-Headers.git", :revision => revi
  end
  resource "Vulkan-Portability" do
    revi = Utils.popen_read("cat #{HOMEBREW_CACHE}/moltenvk--git/ExternalRevisions/Vulkan-Portability_repo_revision").chomp
    url "https://github.com/KhronosGroup/Vulkan-Portability.git", :revision => revi
  end
  resource "SPIRV-Cross" do
    revi = Utils.popen_read("cat #{HOMEBREW_CACHE}/moltenvk--git/ExternalRevisions/SPIRV-Cross_repo_revision").chomp
    url "https://github.com/KhronosGroup/SPIRV-Cross.git", :revision => revi
  end
  resource "glslang" do
    revi = Utils.popen_read("cat #{HOMEBREW_CACHE}/moltenvk--git/ExternalRevisions/glslang_repo_revision").chomp
    url "https://github.com/KhronosGroup/glslang.git", :revision => revi
  end
  resource "Vulkan-Tools" do
    revi = Utils.popen_read("cat #{HOMEBREW_CACHE}/moltenvk--git/ExternalRevisions/Vulkan-Tools_repo_revision").chomp
    url "https://github.com/KhronosGroup/Vulkan-Tools.git", :revision => revi
  end
  resource "glslang_SPIRV-Headers" do
    revi = Utils.popen_read("cat #{HOMEBREW_CACHE}/moltenvk--glslang--git/known_good.json | grep -m2 'commit\"' | tail -n1 | cut -d '\"' -f4").chomp
    url "https://github.com/KhronosGroup/SPIRV-Headers.git", :revision => revi
  end
  resource "glslang_SPIRV-Tools" do
    revi = Utils.popen_read("cat #{HOMEBREW_CACHE}/moltenvk--glslang--git/known_good.json | grep -m2 'commit\"' | head -n1 | cut -d '\"' -f4").chomp
    url "https://github.com/KhronosGroup/SPIRV-Tools.git", :revision => revi
  end

  def install
    ["Vulkan-Headers", "Vulkan-Portability", "SPIRV-Cross", "glslang", "Vulkan-Tools"].each do |r|
      (buildpath/"External/#{r}").install resource(r)
    end

    (buildpath/"External/glslang/External/spirv-tools").install resource("glslang_SPIRV-Tools")
    (buildpath/"External/glslang/External/spirv-tools/external/spirv-headers").install resource("glslang_SPIRV-Headers")

    inreplace "#{buildpath}/Scripts/package_ext_libs.sh",
              "make --quiet clean",
              ""

    inreplace "#{buildpath}/ExternalDependencies.xcodeproj/project.pbxproj",
              "MACOSX_DEPLOYMENT_TARGET = 10.11;",
              "MACOSX_DEPLOYMENT_TARGET = #{MacOS.version};"

    inreplace "#{buildpath}/MoltenVK/MoltenVK.xcodeproj/project.pbxproj" do |s|
      s.gsub! '"\"$(SRCROOT)/../External/cereal/include\"",',
              "\"#{Formula["cereal"].opt_include}\","
      s.gsub! "MACOSX_DEPLOYMENT_TARGET = 10.11;",
              "MACOSX_DEPLOYMENT_TARGET = #{MacOS.version};"
    end

    inreplace "#{buildpath}/MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj",
              "MACOSX_DEPLOYMENT_TARGET = 10.11;",
              "MACOSX_DEPLOYMENT_TARGET = #{MacOS.version};"

    cd "External/glslang/External/spirv-tools" do
      mkdir "build" do
        # "Building SPIRV-Tools"
        system "cmake",
               "-DCMAKE_INSTALL_PREFIX=install",
               "-DCMAKE_BUILD_TYPE=Release",
               "-DPYTHON_EXECUTABLE=#{Formula["python"].opt_bin}/python3",
               "-G",
               "Ninja",
               ".."
        system "ninja"
      end
    end

    xcodebuild "-project",
      "ExternalDependencies.xcodeproj",
      "-scheme",
      "ExternalDependencies-macOS",
      "-derivedDataPath",
      "#{buildpath}/External/build",
      "build",
      "SYMROOT=#{buildpath}/.tmp"

    xcodebuild "-project",
      "MoltenVKPackaging.xcodeproj",
      "-scheme",
      "MoltenVK Package (macOS only)",
      "-derivedDataPath",
      "#{buildpath}",
      "build",
      "SYMROOT=#{buildpath}/.tmp"

    include.install Dir["Package/Release/MoltenVK/include/*"]
    lib.install Dir["Package/Release/MoltenVK/macOS/dynamic/*"]
    lib.install "Package/Release/MoltenVK/macOS/static/libMoltenVK.a"
    frameworks.install "Package/Release/MoltenVK/macOS/framework/MoltenVK.framework"

    include.install Dir["Package/Release/MoltenVKShaderConverter/include/*"]
    lib.install "Package/Release/MoltenVKShaderConverter/MoltenVKGLSLToSPIRVConverter/macOS/dynamic/libMoltenVKGLSLToSPIRVConverter.dylib"
    lib.install "Package/Release/MoltenVKShaderConverter/MoltenVKGLSLToSPIRVConverter/macOS/static/libMoltenVKGLSLToSPIRVConverter.a"
    frameworks.install "Package/Release/MoltenVKShaderConverter/MoltenVKGLSLToSPIRVConverter/macOS/framework/MoltenVKGLSLToSPIRVConverter.framework"

    lib.install "Package/Release/MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/macOS/dynamic/libMoltenVKSPIRVToMSLConverter.dylib"
    lib.install "Package/Release/MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/macOS/static/libMoltenVKSPIRVToMSLConverter.a"
    frameworks.install "Package/Release/MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/macOS/framework/MoltenVKSPIRVToMSLConverter.framework"

    bin.install "Package/Release/MoltenVKShaderConverter/Tools/MoltenVKShaderConverter"
  end

  test do
    (testpath/"test.cpp").write <<~EOS
      #include <vulkan/vulkan.h>
      int main(void)
      {
          const char *extensionNames[] = { "VK_KHR_surface" };
          VkInstanceCreateInfo instanceCreateInfo = {
              VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, NULL,
              0, NULL,
              0, NULL,
              1, extensionNames,
          };
          VkInstance inst;
          vkCreateInstance(&instanceCreateInfo, NULL, &inst);
          return 0;
      }
    EOS
    system ENV.cc, "-o", "test", "test.cpp", "-L#{lib}", "-lMoltenVK"
    system "./test"
  end
end


~~~

Modifications:
- The official script clone the specific dependencies and get the correct revision from the `ExternalRevisions` files. i do the same but using the `resource` options. the correct commit is taked in the same way (but with mimic). including the sub-dependencies used by `glslang`.
- The `xcodebuild` launcher for build the external dependencies is now used directly in the formulae. including the `spirv-tools` build process.
- The code substitutions is now reduced to the minimun necessary, now the external vulkan dependencies is not used in favour of internal copy of the library pulled with the `resource` option. I only keep the external `cereal` dependency
- Also include  the installation rules.

that's all

i know this method is probably not good and poorlry, and should be use the external libs. but seems moltenvk devs don't expect this.

anyone can test it and improve the script? i'm not coder, i take the ideas from the other formulaes and my linux knowledge

greetings

**Comment by rafaga** [comment]
Thanks for you contribution, I think there is a more complicated situation with MoltenVK and should be resolved accordly.

I'm agree with you that KhronosGroup devs expect that every developer use the "official" mechanism to build MoltenVK.

If you check https://github.com/rafaga/homebrew-r2k/commit/d2140764b1700f0d093782e40cdf058f4992ed80 you should note, that I have done some similiar in the past, later of thinking further, I decided go against this approach because:

- The problem using MoltenVk as-is or using as resources is that creates version fragmentation in their dependencies. Example: spirv-headers/spirv-tools its head revision go futher the recomemded version by MoltenVK, anyone cloning the repo will to compile the library or headers (because there is genuine reasons to get the dependencies without MoltenVK) will get a version that is not recommeded. Using the release files in the github repo will get you a version behind the recomended version in MoltenVK. Then if you compile MoltenVK linked against a spirv-headers/spirv-tools version that is not the most recent in repo and not the last offcial release from the git repo. This will produce some nasty side-effects.

- Using libglslang, spirv-tools, spirv-cross, and the vulkan SDK via resources or fetchdependencies limit its usage to only MoltenVK, and because are libraries designed to give a more wide functionality and not merely being a dependency of MoltenVK can be used by other developers to build cross-plataform applications, limiting the use of these libraries, will force o the developers to build another copy of the dependencies and in the long term that doesn't benefit nobody.

- I know that replacing heavy chunks of code in the config files is not a very robust approach but the idea is making the build system more dependant of the system wide libraries and not the local fectched code and I'm thinking in the long term propose pull request to enhance the build files in each library.

- In paper using reference of the libraries via pkg-config in xcodebuild, should not be very dificult, personally I don't have much experience using xcodebuild. I need to figure out how to invoke the libraries correctly. Recently I created a patch to create a file named `glslang.pc` that will give glslang the functionality of being linked in system-wide scope, all this with the objetive of fixing the linkage problems in MoltenVK.

I thank you for your proposal, but I'm not agree of following this approach for the reasons exposed previously.
